all:
	g++ -o runedf main.cpp Task.cpp TaskSet.cpp EdfAlgorithm.cpp 

testtaskset:
	g++ -o testtaskset test.cpp Task.cpp  TaskSet.cpp

testtask:
	g++ -o testtask test.cpp Task.cpp  

testedf:
	g++ -o testedf test.cpp Task.cpp EdfAlgorithm.cpp TaskSet.cpp

